# Generated by Django 5.1.3 on 2025-02-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoogleTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата продажи"
                    ),
                ),
                (
                    "last_change_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата последней продажи"
                    ),
                ),
                (
                    "total_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Сумма"
                    ),
                ),
                (
                    "discount_percent",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Процент скидки"
                    ),
                ),
                (
                    "warehouse_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Название склада",
                    ),
                ),
                (
                    "oblast",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Область РФ"
                    ),
                ),
                (
                    "nm_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Продукт ID"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Категория"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Бренд"
                    ),
                ),
                (
                    "is_cancel",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Закончилось на складе"
                    ),
                ),
                (
                    "cancel_dt",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата когда закончилось"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Тип продажи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
