# Generated by Django 5.1.3 on 2025-02-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testalmikeev", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="googletab",
            name="link",
            field=models.TextField(default=123, verbose_name="Ссылка на таблицу"),
            preserve_default=False,
        ),
    ]
