# Generated by Django 5.1.3 on 2025-02-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testalmikeev", "0002_googletab_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googletab",
            name="link",
        ),
    ]
