# Generated by Django 5.1.3 on 2025-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testalmikeev", "0003_remove_googletab_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileCsv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="CSV файл",
                    ),
                ),
            ],
        ),
    ]
