# Generated by Django 5.1.3 on 2025-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testalmikeev", "0006_alter_googletab_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googletab",
            name="total_price",
            field=models.FloatField(blank=True, null=True, verbose_name="Сумма"),
        ),
    ]
